-- MySQL Script generated by MySQL Workbench
-- 08/03/17 14:54:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdInventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdInventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdInventario` DEFAULT CHARACTER SET utf8 ;
USE `bdInventario` ;

-- -----------------------------------------------------
-- Table `bdInventario`.`DatosPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdInventario`.`DatosPersona` (
  `idDatosPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Documento` INT NOT NULL,
  `nombres` VARCHAR(70) NOT NULL,
  `apellidos` VARCHAR(70) NOT NULL,
  `fechaNacimiento` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefonoCelular` VARCHAR(45) NOT NULL,
  `Estado` ENUM('ACTIVO', 'INACTIVO') NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `Perfil` ENUM('ADMINISTRADOR', 'JEFEBODEGA', 'TRBAJADOR') NOT NULL,
  PRIMARY KEY (`idDatosPersona`),
  UNIQUE INDEX `idDatosPersona_UNIQUE` (`idDatosPersona` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdInventario`.`DatosElemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdInventario`.`DatosElemento` (
  `idElemento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `descripcion` TEXT(250) NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` ENUM('ACTIVO', 'INACTIVO') NOT NULL,
  `tipo` VARCHAR(80) NOT NULL,
  `ubicacionBodega` VARCHAR(100) NULL,
  PRIMARY KEY (`idElemento`),
  UNIQUE INDEX `idDatosElemento_UNIQUE` (`idElemento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdInventario`.`SalidaElemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdInventario`.`SalidaElemento` (
  `idSalidaElemento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `fechaHora` VARCHAR(25) NOT NULL,
  `documentoTrabajador` INT NULL,
  `nombreTrabajador` VARCHAR(140) NOT NULL,
  `Observaciones` TEXT(250) NULL,
  PRIMARY KEY (`idSalidaElemento`),
  UNIQUE INDEX `idSalidaElemento_UNIQUE` (`idSalidaElemento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdInventario`.`EntradaElemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdInventario`.`EntradaElemento` (
  `idEntradaElemento` INT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `fechaHora` VARCHAR(45) NOT NULL,
  `documentoTrabajador` INT NOT NULL,
  `nombreTrabajador` VARCHAR(140) NOT NULL,
  `estado` ENUM('BUENO', 'MAL ESTADO', 'PERDIDO') NOT NULL,
  `observaciones` TEXT(250) NULL,
  PRIMARY KEY (`idEntradaElemento`),
  UNIQUE INDEX `idEntradaElemento_UNIQUE` (`idEntradaElemento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdInventario`.`Historal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdInventario`.`Historal` (
  `idHistoral` INT NOT NULL AUTO_INCREMENT,
  `elementoPrestados` VARCHAR(70) NOT NULL,
  `codigo` INT NOT NULL,
  `trabajador` VARCHAR(140) NOT NULL,
  `fechaHoraPresta` VARCHAR(25) NOT NULL,
  `fechaHoraEntrega` VARCHAR(25) NOT NULL,
  `observaciones` TEXT(250) NULL,
  PRIMARY KEY (`idHistoral`),
  UNIQUE INDEX `idHistoral_UNIQUE` (`idHistoral` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
